- name: Install X Window System with yum
  yum:
    name: "@X Window System"
    state: present

- name: Install GNOME Desktop with yum
  yum:
    name:
      - gnome-classic-session
      - gnome-terminal
      - control-center
      - liberation-mono-fonts
    state: present

- name: Install ibus-kkc（a Japanese Kana Kanji input engine for IBus）with yum
  yum:
    name: ibus-kkc
    state: present

- name: Install VL Gothic Font Family with yum
  yum:
    name: vlgothic-*
    state: present

- name: Install TigerVNC Server with yum
  yum:
    name: 'tigervnc-server'
    state: present

- name: Copy configuration file
  copy:
    src: /lib/systemd/system/vncserver@.service
    dest: /etc/systemd/system/vncserver@:1.service
    remote_src: yes

- name: Configure connecting user settings
  replace:
    dest: /etc/systemd/system/vncserver@:1.service
    regexp: '<USER>'
    replace: "{{ vnc_user }}"

- name: Add VNC user to system
  user:
    name: "{{ vnc_user }}"
    password: "{{ vnc_password }} | password_hash('sha512')"

- name: Create $HOME/.vnc directory
  file:
    path: "/home/{{ vnc_user }}/.vnc"
    state: directory
    owner: '{{ vnc_user }}'
    group: '{{ vnc_user }}'
    mode: 0755

- name: Set default password
  shell: "echo {{ vnc_password }} | vncpasswd -f > /home/{{ vnc_user }}/.vnc/passwd"

- name: Change permission of password settings file
  file:
    path: "/home/{{ vnc_user }}/.vnc/passwd"
    state: file
    owner: '{{ vnc_user }}'
    group: '{{ vnc_user }}'
    mode: 0600

- name: Start and enable VNC server
  systemd:
    name: vncserver@:1.service
    state: started
    enabled: yes
    daemon_reload: yes
